### ISSUE TITLE
【バグ】 店に入店すると AddressSanitizer により強制終了

### ISSUE THREAD

**Issue by habu1010** [hengband/hengband#2235]
## 環境

- OS: WSL2 on Ubuntu on Windows 10
- バージョン: 現在の develop ブランチ最新 

## バグの詳細

店に入店すると AddressSanitizer がエラーを出力してゲームが強制終了する

## 再現手順

バグを発生させる手順が分かっていれば記載

1. AddressSanitizer を有効にして hengband をビルド
2. ゲームを開始する
3. 店に入店すると AddressSanitizer が下記のエラーを出力してゲームが強制終了する

```
=================================================================
==8182==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x617000002d34 at pc 0x56314b6e9228 bp 0x7ffeedbb68f0 sp 0x7ffeedbb68e0
READ of size 4 at 0x617000002d34 thread T0
    #0 0x56314b6e9227 in store_create(PlayerType*, short, bool (*)(PlayerType*, ObjectType*), bool (*)(PlayerType*, ObjectType const*), void (*)(PlayerType*, ObjectType*)) store/store-util.cpp:151
    #1 0x56314b6cfebe in store_maintenance(PlayerType*, int, StoreSaleType, int) store/store.cpp:353
    #2 0x56314b6d4bb2 in do_cmd_store(PlayerType*) store/cmd-store.cpp:97
    #3 0x56314ad468a7 in process_command(PlayerType*) io/input-key-processor.cpp:291
    #4 0x56314aa21dbd in process_player(PlayerType*) core/player-processor.cpp:316
    #5 0x56314aa4633d in process_dungeon(PlayerType*, bool) dungeon/dungeon-processor.cpp:171
    #6 0x56314aa13327 in process_game_turn core/game-play.cpp:342
    #7 0x56314aa140bd in play_game(PlayerType*, bool, bool) core/game-play.cpp:417
    #8 0x56314ae98ed6 in main /home/habu/hengband/src/main.cpp:565
    #9 0x7f005904d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x56314a752d5d in _start (/home/habu/hengband/src/hengband+0x2738d5d)

0x617000002d34 is located 20 bytes to the right of 672-byte region [0x617000002a80,0x617000002d20)
allocated by thread T0 here:
    #0 0x7f005a1d5f27 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x56314b6f45fd in __gnu_cxx::new_allocator<owner_type>::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x56314b6f32e9 in std::allocator_traits<std::allocator<owner_type> >::allocate(std::allocator<owner_type>&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x56314b6f1d8f in std::_Vector_base<owner_type, std::allocator<owner_type> >::_M_allocate(unsigned long) /usr/include/c++/10/bits/stl_vector.h:346
    #4 0x56314b6f33c8 in std::_Vector_base<owner_type, std::allocator<owner_type> >::_M_create_storage(unsigned long) /usr/include/c++/10/bits/stl_vector.h:361
    #5 0x56314b6f1fee in std::_Vector_base<owner_type, std::allocator<owner_type> >::_Vector_base(unsigned long, std::allocator<owner_type> const&) /usr/include/c++/10/bits/stl_vector.h:305
    #6 0x56314b6f10f3 in std::vector<owner_type, std::allocator<owner_type> >::vector(std::vector<owner_type, std::allocator<owner_type> > const&) /usr/include/c++/10/bits/stl_vector.h:555
    #7 0x56314b6f84b7 in std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >::pair(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&) /usr/include/c++/10/bits/stl_pair.h:314
    #8 0x56314b6f8553 in void __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> >::construct<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&>(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >*, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&) /usr/include/c++/10/ext/new_allocator.h:150
    #9 0x56314b6f7a9b in void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> > >::construct<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&>(std::allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> >&, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >*, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&) /usr/include/c++/10/bits/alloc_traits.h:512
    #10 0x56314b6f7005 in std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> > >::_M_allocate_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&>(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&) /usr/include/c++/10/bits/hashtable_policy.h:2037
    #11 0x56314b6f5f39 in std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false>* std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> > >::operator()<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&>(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&) const /usr/include/c++/10/bits/hashtable_policy.h:167
    #12 0x56314b6f50d1 in std::pair<std::__detail::_Node_iterator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false, false>, bool> std::_Hashtable<StoreSaleType, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > >, std::__detail::_Select1st, std::equal_to<StoreSaleType>, std::hash<StoreSaleType>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> > > >(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, false> > > const&, std::integral_constant<bool, true>, unsigned long) /usr/include/c++/10/bits/hashtable.h:1813
    #13 0x56314b6f4185 in std::__detail::_Insert_base<StoreSaleType, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > >, std::__detail::_Select1st, std::equal_to<StoreSaleType>, std::hash<StoreSaleType>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::insert(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const&) /usr/include/c++/10/bits/hashtable_policy.h:840
    #14 0x56314b6f2c04 in std::_Hashtable<StoreSaleType, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > >, std::__detail::_Select1st, std::equal_to<StoreSaleType>, std::hash<StoreSaleType>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_Hashtable<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const*>(std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const*, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > const*, unsigned long, std::hash<StoreSaleType> const&, std::__detail::_Mod_range_hashing const&, std::__detail::_Default_ranged_hash const&, std::equal_to<StoreSaleType> const&, std::__detail::_Select1st const&, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > > const&) /usr/include/c++/10/bits/hashtable.h:1037
    #15 0x56314b6f15ae in std::_Hashtable<StoreSaleType, std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > >, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > >, std::__detail::_Select1st, std::equal_to<StoreSaleType>, std::hash<StoreSaleType>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_Hashtable(std::initializer_list<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > >, unsigned long, std::hash<StoreSaleType> const&, std::equal_to<StoreSaleType> const&, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > > const&) /usr/include/c++/10/bits/hashtable.h:504
    #16 0x56314b6f0440 in std::unordered_map<StoreSaleType, std::vector<owner_type, std::allocator<owner_type> >, std::hash<StoreSaleType>, std::equal_to<StoreSaleType>, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > > >::unordered_map(std::initializer_list<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > >, unsigned long, std::hash<StoreSaleType> const&, std::equal_to<StoreSaleType> const&, std::allocator<std::pair<StoreSaleType const, std::vector<owner_type, std::allocator<owner_type> > > > const&) /usr/include/c++/10/bits/unordered_map.h:231
    #17 0x56314b6ee8a7 in __static_initialization_and_destruction_0 store/store-owners.cpp:8
    #18 0x56314b6efa79 in _GLOBAL__sub_I_owners store/store-owners.cpp:525
    #19 0x56314b90a7bc in __libc_csu_init (/home/habu/hengband/src/hengband+0x38f07bc)

SUMMARY: AddressSanitizer: heap-buffer-overflow store/store-util.cpp:151 in store_create(PlayerType*, short, bool (*)(PlayerType*, ObjectType*), bool (*)(PlayerType*, ObjectType const*), void (*)(PlayerType*, ObjectType*))
Shadow bytes around the buggy address:
  0x0c2e7fff8550: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8560: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8570: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8590: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2e7fff85a0: 00 00 00 00 fa fa[fa]fa fa fa fa fa fa fa fa fa
  0x0c2e7fff85b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff85c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff85d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff85e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff85f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==8182==ABORTING
```

## 期待される正常な動作

店に入店でき、アイテムの売買ができる

## 補足事項

店のオーナーの構造のリファクタリングをしていたので、それが原因っぽいように思う

**Comment by habu1010** [comment]
やはり #2206 が原因。
リファクタリング前のセーブファイルの場合、下記の部分で st_ptr->owner が店舗情報を削った要素の部分を指している可能性があり、その場合配列外アクセスとなる。
リリースが近いのでひとまず一旦 #2206 を Revert しておき、後ほど改めて対応策を考える。

https://github.com/hengband/hengband/blob/b37c167a0bd97022338f3bd4ce0052c697866c92/src/store/store-util.cpp#L136

**Comment by habu1010** [comment]
Revert のマージで自動クローズされたが、改めて対応策をこの Issue でやることにするので Reopen しておきます。

**Comment by sikabane-works** [comment]
リバート戻しと既存セーブデータファイルで参照外エラー起こす問題、こちらで修正してみます。
